version: "3"
services:
  redbrick:
    image: 'redbrick/site:latest'
    container_name: 'redbrick-site'
    command: 'yarn docker'
    restart: 'always'
    volumes:
      - $PWD/logs:/usr/src/app/logs
      - $PWD/public:/usr/src/app/public
    ports:
      - '3000:3000'
    env_file: .env
